# Generated by Django 6.0.5 on 2026-05-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_linkdin_url_userprofile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Recruiter', 'Recruiter'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
